/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/common-ui/Button.vue')['default']
    Footer: typeof import('./src/components/popup/Footer.vue')['default']
    Pager: typeof import('./src/components/popup/Pager.vue')['default']
    Progress: typeof import('./src/components/Progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
